algoritmo "semnome"
// Função : Ler os valores de X e Y e calcular a soma da série descrita no
// código
// Autor : Lucas Mateus Midão Fernandes
// Data : 05/05/2015
// Seção de Declarações 
var
I: inteiro
x,y,s: real
inicio
// Entrada - Leitura de dados
escreval("Digite o valor de X: ")
leia(x)
escreval("Digite o valor de Y: ")
leia(y)
s <- 0
// Processamento - cálculo da soma da série
para I de 10 ate 1 faca
 s <- (x/I)
fimalgoritmo
