algoritmo "Números Positivos"
// Função : Indentificar se um número é positivo
// Autor : Lucas Mateus Midão Fernandes
// Data : 14/04/2015
// Seção de Declarações
var
I, Num: Inteiro
inicio
// Entrada - Leitura de dados e processamento
Para I de 1 ate 10 passo 1 faca
   escreval("Digite um número: ")
   leia(Num)
   se (Num > 0) entao
      escreval("O número", Num," é positivo.")
   fimse
fimpara
fimalgoritmo
