algoritmo "Conversão Fahrenheit para Celsius"
// Função : Converter 50 a 150 graus Fahrenheit para graus Celsius
// Autor : Lucas Mateus Midão Fernandes
// Data : 10/5/2015
// Seção de Declarações
var
I: inteiro
C: real
inicio
// Entrada - Leitura de dados
para I de 50 ate 150 faca
   escreval("O valor em Fahrenheit é igual a: ", I,"°F")
   C <- ((I-32)*5)/9
   escreval("Convertendo para Celsius temos: ", C,"°C")
fimpara
fimalgoritmo
